name: Deploy JSON Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install json-server
        run: npm install -g json-server

      - name: Start json-server
        run: json-server --watch db.json
